version: "3.8"

services:
  nginx:
    build:
      context: ./contaners/nginx
      dockerfile: Dockerfile
    container_name: klavera-nginx
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: ./contaners/fpm
      dockerfile: Dockerfile
    container_name: klavera-php
    restart: no
    volumes:
      - ./src:/var/www/html
    expose:
      - "9000"
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: klavera-my_postgres
    restart: no
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-php_docker}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mysecretpassword}
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog:latest #используем официальный образ
    container_name: klavera-mailhog
    ports:
      - "127.0.0.1:1025:1025"  # SMTP
      - "127.0.0.1:8025:8025"  # web-interface
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
